### ISSUE TITLE
Feature: Couple 연동 기능 구현

### ISSUE THREAD

**Issue by lcomment** [wooda-ege/lovebird-backend#30]
## Description

> 커플 연동 기능 구현

## To-do

- [x] 코드 생성 기능
- 코드 공유 기능 (카카오 메시지) → ***REST API 미지원으로 인한 삭제***
- [x] 커플 연동 기능
- [x] 코드 자동 할당 해제 기능 (Spring Scheduler 활용)
